# Instance 1

Optimisons un portefeuille sur une période, soit N=1.

Nous choisissons un portefeuille constitué de:
- 1 actif sans risque avec un rendement de 8%,
- n=2 actifs risqués tel que:
  actif risqué 1: rendement equiprobable parmi les valeurs de 15% et de 5%, noté r1,
  actif risqué 2: rendement equiprobable parmi les valeurs de 20% et de 1%, noté r2

L'aversion au risque de l'investisseur est traduite par la fonction d'utilité logarithmique suivante:
u(x)=ln(a+x) où a=1, coefficient d'aversion au risque

In [19]:
import numpy as np

I=1000 #nombre de simulations
x_0=1000 #richesse initiale

N=1 #nombre de periodes
n=2 #nombre d'actifs risqués
a=1 #coefficient d'aversion au risque

r0 = 0.08 #rendement net de l'actif sans risque
s = r0 + 1 #rendement brut de l'actif sans risque
r1 = [0.05, 0.15] #rendements nets de l'actif risqué 1
r2 = [0.01, 0.20] #rendements nets de l'actif risqué 2
pi= 0.5 #pi équiprobabilite des rendements

In [20]:
# Fonction pour simuler le rendement d'un actif risqué.
# Entrées:
#   r: liste des rendements des actifs risqués.
def actif(r):     
    lu=np.random.rand()  #simulation d'une loi uniforme sur l'intervalle [0,1]
    if lu>pi :       
        return r[1]   #rendement de l'actif 1 dans le bon état de la nature, car 15% > 8% du rendement sans risque
    else:
        return r[0]    #rendement de l'actif 1 dans le mauvais état de la nature, car 5% < 8% du rendement sans risque

In [21]:
# Fonction pour déterminer les meilleurs proportions de richesse à investir dans les différents actifs.
# Cette fonction renvoit aussi le montant de la richesse espérée par ces investissement.   
# Entrées:
#   x_0: richesse initiale à investir dans les différents actifs,
#   a: coefficient d'aversion au risque de l'utilité log(a+x),
#   r_actif_sans_risque: taux de rendement de l'actif sans risque
def politique_optimale(x_0, a, r_actif_sans_risque):
    # Init du portefeuille pour chacune des simulations de proportions
    # 1ere colonne: proportion de richesse déposée dans l'actif 1,
    # 2e colonne: proportion de richesse déposée dans l'actif 2,
    # 3e colonne: utilité espérée.  
    tableau_u_j=np.zeros((I,n+1))
               
    # Executions de I simulations de proportions aléatoires différentes
    for i in range (0,I):
        tableau_u_j[i,0]=np.random.rand() #proportion simulée pour l'actif 1
        tableau_u_j[i,1]=(1-tableau_u_j[i,0])*np.random.rand() #proportion simulée pour l'actif 2
        
        #Init de la fonction d'utilité pour la simulation en cours
        utilité_x=np.zeros(I)
        
        # Executions de I nouvelles simulations pour définir des rendements différents pour la proportion courante
        for p in range(0,I):
            u1 = x_0*tableau_u_j[i,0]  #Montant investi dans l'actif 1
            u2 = x_0*tableau_u_j[i,1]  #Montant investi dans l'actif 2
            e1 = 1 + actif(r1)  #rendement brut simulé de l'actif 1
            e2 = 1 + actif(r2)  #rendement brut simulé de l'actif 2
            x = x_0*s + (e1-s)*u1 + (e2-s)*u2  #richesse après investissement dépendemment des rendements simulés            
            utilité_x[p]=np.log(a+x)  #calcul de l'utilité
        tableau_u_j[i,2]=np.mean(utilité_x)  #Moyenne de l'utilité sur l'ensemble des rendements simulés 
    # Calcul des montants optimaux à investir
    i_star=np.argmax(tableau_u_j[:,2]) #Index de la proportion qui maximise la moyenne des utilités: correspond à l'utilité maximale
    u1_star = x_0*tableau_u_j[i_star,0]  #Montant optimal à investir pour l'actif 1
    u2_star = x_0*tableau_u_j[i_star,1]  #Montant optimal à investir l'actif 2
    
    vect_x1=np.zeros(I)
    # Calcul de la richesse espérée en utilisant les proportions qui maximisent l'espérance de l'utilité
    for i in range (0,I):
        e1 = 1 + actif(r1)  #rendement brut simulé de l'actif 1
        e2 = 1 + actif(r2)  #rendement brut simulé de l'actif 2
        vect_x1[i] = u1_star*e1 + u2_star*e2 + (s)*(x_0 - u1_star - u2_star) #richesse après investissement optimal dépendemment des rendements simulés
    x1=np.mean(vect_x1)  #richesse espérée sur l'ensemble des rendements simulés avec investissement optimal 
    string="Portion optimale à investir dans les deux actifs risqués, Richesse espérée"
    
    return tableau_u_j[i_star,0:2], x1

In [22]:
u_star, x1 = politique_optimale(x_0, a, r0)
print("Proportions optimales à investir dans les deux actifs risqués:")
print("[Proportion actif1, Proportion actif2]")
print(u_star)
print(" ")
print("Richesse espérée:")
print(x1)

Proportions optimales à investir dans les deux actifs risqués:
[Proportion actif1, Proportion actif2]
[0.13385576 0.81621215]
 
Richesse espérée:
1103.6570367580678


# Instance 2

Optimisons un portefeuille sur trois périodes, soit N=3.

Nous choisissons un portefeuille constitué de:
- 1 actif sans risque avec un rendement de 8%,
- n=2 actifs risqués tel que:
  actif risqué 1: rendement equiprobable parmi les valeurs de 15% et de 5%, noté r1,
  actif risqué 2: rendement equiprobable parmi les valeurs de 20% et de 1%, noté r2

L'aversion au risque de l'investisseur est traduite par la fonction d'utilité logarithmique suivante:
u(x)=ln(a+x) où a=1, coefficient d'aversion au risque




Si on a besoin d'une valeur de xk on prendrera 1000
on prendrera 1000 pour x0 et on suppose que tout notre argent est dans l'actif sans risque 
donc on prendra xk= 1000*(1,08)^(k)

La politique optimal est de toujours maximiser l'utilité de la richesse au temps N pour tous les temps k de 1 à N

In [23]:
# Toutes les constantes definies dans l'Instance 1 sont conservees, sauf N:
N = 3

In [24]:
# Init du portefeuille optimale pour chacune des N périodes
#1ere colonne: proportion optimale de richesse déposée dans l'actif 1,
#2e colonne: proportion optimale de richesse déposée dans l'actif 2,
#3e colonne: richesse espérée pour la proportion optimale 
portefeuille_optimal=np.zeros((N, n+1))
                                        
# Chainage arriere sur les N périodes
for k in range (N-1,-1,-1):
    # Init du portefeuille pour chacune des simulations de proportions à la periode k
    # 1ere colonne: proportion de richesse déposée dans l'actif 1
    # 2e colonne: proportion de richesse déposée dans l'actif 2,
    # 3e colonne: utilité espérée.  
    tableau_u_j = np.zeros((I,n+1))
    
    # Executions de I simulations de proportions aléatoires différentes
    for i in range (0,I):                           
        tableau_u_j[i,0]=np.random.rand() #proportion simulée pour l'actif 1
        tableau_u_j[i,1]=(1-tableau_u_j[i,0])*np.random.rand() #proportion pour de l'actif 2
        
        #Init de la fonction d'utilité pour la simulation en cours
        uxN=np.zeros(I)
        
        # Executions de I nouvelles simulations pour définir des rendements différents pour la proportion courante
        for p in range(0,I):
            u1 = tableau_u_j[i,0]*x_0 #Montant investi dans l'actif 1
            u2 = tableau_u_j[i,0]*x_0 #Montant investi dans l'actif 2
            e1 = 1 + actif(r1)  #rendement brut simulé de l'actif 1
            e2 = 1 + actif(r2)  #rendement brut simulé de l'actif 2
            
            xN = s**(N-k)*x_0*s**(k) + ( (e1-s)*u1 + (e2-s)*u2 )*s**(N-1-k) #contribution à la richesse de la période k à la période N 
            #Actualisation de la richesse à la periode N par sommation des contributions des richesses des périodes N-1 à k+1
            for j in range(N-1,k,-1):
                u_opt1 = portefeuille_optimal[j,0] #Montant investi dans l'actif 1 à la période j
                u_opt2=portefeuille_optimal[j,1] #Montant investi dans l'actif 2 à la période j
                e1 = 1 + actif(r1)  #rendement brut simulé de l'actif 1
                e2 = 1 + actif(r2)  #rendement brut simulé de l'actif 2
                xN += ( (e1-s)*u_opt1+ (e2-s)*u_opt2 )*s**(N-1-j) #actualisation de la richesse à la periode N
            uxN[p] = np.log(a+xN)  #calcul de l'utilité
        tableau_u_j[i,2] = np.mean(uxN)  #Moyenne de l'utilité sur l'ensemble des rendements simulés
    istar=np.argmax(tableau_u_j[:,-1])  #Index de la proportion qui maximise la moyenne des utilités: correspond à l'utilité maximale
    portefeuille_optimal[k,0] = tableau_u_j[istar,0] #proportion optimale pour l'actif 1 à la période k
    portefeuille_optimal[k,1] = tableau_u_j[istar,1] #proportion optimale pour l'actif 2 à la période k

# Init de la richesse esperée à la richesse initiale x_0
richesse = x_0
# Calcul des richesses esperées pour chaque période k avec le portefeuille optimal associé pour toutes les simulations de rendements aléatoires
for k in range(0,N):
    xk=np.zeros(I)
    # Calcul de la richesse espérée à la période k en utilisant les proportions qui maximisent l'espérance de l'utilité
    for i in range (0,I): 
        e1=1+actif(r1) #rendement brut simulé de l'actif 1
        e2=1+actif(r2) #rendement brut simulé de l'actif 2
        # Calcul des montants optimaux à investir à la période k
        u1 = richesse*portefeuille_optimal[k,0] #Montant optimal à investir pour l'actif 1
        u2 = richesse*portefeuille_optimal[k,1] #Montant optimal à investir pour l'actif 2
        xk[i] = u1*e1 + u2*e2 + (richesse-u1-u2)*s #richesse après investissement optimal dépendemment des rendements simulés
    #richesse espérée sur l'ensemble des rendements simulés avec investissement optimal à la période k
    richesse=np.mean(xk)
    portefeuille_optimal[k,-1]=np.mean(xk)

print("Proportions optimales à investir dans les deux actifs risqués pour chaque période et richesse espérée associée :")
print("[Proportion actif1, Proportion actif2, Richesse espérée]")
print(portefeuille_optimal)

Proportions optimales à investir dans les deux actifs risqués pour chaque période et richesse espérée associée :
[Proportion actif1, Proportion actif2, Richesse espérée]
[[9.59028053e-01 2.36680185e-02 1.10118832e+03]
 [9.82142142e-01 1.03013387e-02 1.20942175e+03]
 [9.48587341e-01 3.83139350e-02 1.32867290e+03]]


In [25]:
# Calcul de la richesse obtenue en plaçant toute la richesse intiale dans l'actif sans risque à la période N  
x_0*s**N

1259.7120000000002

## CONCLUSION
La richesse espérée obtenue à la période N est bien superieure au montant qu'on obtiendrait en plaçant toute la richesse intiale dans l'actif sans risque  